from execution.executor import executor


class EngineeringExecutorStage:
    """
    Executes the engineering plan.

    This stage performs the actions generated by the planner
    and stores every result inside the engineering context.
    """

    def execute(self, context):

        print("[Executor] Executing engineering plan...")

        context.history = []

        for index, step in enumerate(context.plan, start=1):

            action = step.get("action", "<unknown>")

            print(f"[{index}/{len(context.plan)}] {action}")

            try:
                result = executor.execute(step)

                context.history.append({
                    "step": index,
                    "action": action,
                    "success": True,
                    "result": result
                })

            except Exception as e:

                context.history.append({
                    "step": index,
                    "action": action,
                    "success": False,
                    "error": str(e)
                })

                context.error = str(e)

                break

        return context


engineering_executor_stage = EngineeringExecutorStage()